spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_project?characterEncoding=utf-8&useSSL=false
    username: root
    password: 13467477002Xie
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

#server:
#  servlet:
#    context-path: /bookproject
#  port: 8080
server:
  port: 8080
  context-path: /bookproject
